# Generated by Django 6.0.6 on 2026-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['state'], name='routes_fuel_state_172b38_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['city'], name='routes_fuel_city_8cc19a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['retail_price'], name='routes_fuel_retail__88f3a7_idx'),
        ),
    ]
